# -*- coding: utf-8 -*-
"""AP CSP Environmental Injustice Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_APRf9lCI4X4vl4nVlylb8VDxPXqGBq-

**Necessary packs/resources while getting started**

Air Pollution Data (PM2.5 levels per region) --> air_quality.csv

Income Data (Median income per region) --> income_levels.csv

Geospatial Data (Shapefiles for mapping regions) --> regions_shapefile.shp

***Importing Libraries***
"""

import pandas as pd
import geopandas as gpd
import folium
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""**Loading Data**"""

pollution_data=pd.read_csv("nj_air_quality.csv")  # Must include: Region, PM2.5, Latitude, Longitude
income_data=pd.read_csv("income_levels.csv")  # Must include: Region, Median_Income
geo_data = gpd.read_file("regions_shapefile.shp")  # Must include: Region and geometry

# Preview
print(pollution_data.head())
print(income_data.head())
print(geo_data.head())

#Clean column names
for df in [pollution_data, income_data, geo_data]:
    df.columns = df.columns.str.lower().str.strip()

#Clean 'county' VALUES
pollution_data['County'] = pollution_data['county'].str.strip().str.lower()
income_data['County'] = income_data['county'].str.strip().str.lower()
geo_data['County'] = geo_data['county'].str.strip().str.lower()

#Merge pollution and income data on 'county'
pollution_income = pd.merge(pollution_data, income_data, on='county', how='inner')

#Merge with GeoDataFrame (adds geometry)
full_merged = geo_data.merge(pollution_income, on='county', how='inner')

#Save merged data as GeoJSON for the interactive map
full_merged.to_file("merged_nj_pollution_income.geojson", driver="GeoJSON")

print(pollution_data.columns)
print(income_data.columns)
print(geo_data.columns)

full_merged.rename(columns={"micrograms per cubic meter (pm2.5)(1)": "pm2.5"}, inplace=True)

print(full_merged.columns)

# Group by county
county_grouped = full_merged.groupby('county').agg({
    'pm2.5': 'mean',           # Proportion of sites with pollution
    'median_income': 'mean'              # Average median income per county
}).reset_index()

# Rename for clarity
county_grouped.rename(columns={'median_income': 'average_income', 'pm2.5': 'pollution_rate'}, inplace=True)

# Preview
print(county_grouped.head())

print("Pollution dataset counties:")
print(full_merged['county'].unique())

print("\nIncome dataset counties:")
print(full_merged['county'].dropna().unique())  # or use income_data['Region'] if not yet merged

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.regplot(data=county_grouped, x='average_income', y='pollution_rate', scatter_kws={'s': 60}, line_kws={'color': 'red'})
plt.title("Correlation Between County Income and Pollution Presence")
plt.xlabel("Average Median Income by County ($)")
plt.ylabel("Proportion of Sites with Pollution (PM2.5)")
plt.grid(True)
plt.show()

"""**Heat Map Interactive** - should run when regions are specified/renamed"""

# Standardize all columns
for df in [pollution_data, income_data, geo_data]:
    df.columns = df.columns.str.lower().str.strip()

# Merge
merged_data = pd.merge(pollution_data, income_data, on='county', how='inner')

# Map creation
m = folium.Map(location=[40.0583, -74.4057], zoom_start=8)

# Add heatmap (AFTER defining `m`)
heat_data = [
    [row['site latitude'], row['site longitude'], row['daily mean pm2.5 concentration']]
    for _, row in merged_data.iterrows()
]
HeatMap(heat_data).add_to(m)

# Add circle markers
for _, row in merged_data.iterrows():
    folium.CircleMarker(
        location=[row['site latitude'], row['site longitude']],
        radius=7,
        color='red' if row['daily aqi value'] > 100 else 'green',
        fill=True,
        fill_opacity=0.7,
        tooltip=f"""<b>County:</b> {row['county'].capitalize()}<br>
                    <b>PM2.5:</b> {row['daily mean pm2.5 concentration']} µg/m³<br>
                    <b>AQI:</b> {row['daily aqi value']}<br>
                    <b>Median Income:</b> ${row['value (dollars)']}<br>
                    <b>Income Rank:</b> {row['rank within']}"""
    ).add_to(m)

m.save("nj_pollution_income_map.html")
print("Map saved as 'nj_pollution_income_map.html'")

# Step 8: Add Circle Markers for PM2.5
for _, row in full_merged.iterrows():
    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=6,
        color='red' if row['pm2.5'] > 12 else 'green',
        fill=True,
        fill_opacity=0.6,
        tooltip=folium.Tooltip(f"""
            <b>County:</b> {row['county'].capitalize()}<br>
            <b>PM2.5:</b> {row['pm2.5']} µg/m³<br>
            <b>Median Income:</b> ${row['median_income']}
        """, sticky=True)
    ).add_to(m)

# Step 9: Add layer control and save
folium.LayerControl().add_to(m)
m.save("interactive_nj_county_map.html")
print("Interactive map saved as 'interactive_nj_county_map.html'")

from IPython.display import IFrame

# Displays map in the notebook, but should still work outside of Colab
IFrame("nj_pollution_income_map.html", width=800, height=600)
